### ISSUE TITLE
No readme

### ISSUE THREAD

**Issue by 2-bithacker** [FraMecca/CipollaMod#2]
I didn't see a readme on how to install anywhere, so I can't install.  The source code isn't set up like a normal sauermod, and the makefile doesn't seem to do anything.  Please help!

**Comment by FraMecca** [comment]
This is a WIP that is not going to be completed in the foreseeable future, especially because it needs to be refactored for the new sauerbraten version. Sorry but for the moment I suggest you to read the code.

**Comment by 2-bithacker** [comment]
Thanks.  I have never seen a .nim file in source code before.
